# Generated by Django 3.2.4 on 2021-07-10 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='modified_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
