# Generated by Django 3.2.4 on 2021-07-17 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('b', '0004_auto_20210718_0017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='img',
            field=models.ImageField(blank=True, upload_to='bb/%Y/%m/%d2014'),
        ),
    ]
